// Blueprint ตัวอย่าง (demo) — ทำให้เหมือนเล่มจริงที่ Gemini เจน เพื่อให้ลูกค้าเห็นคุณค่า 490฿
// รองรับ 2 ภาษา: sampleBlueprint("th"|"en") — หน้า demo ฝรั่งกด "ดูตัวอย่าง" จะเห็น EN
const DATA = {
  th: {
    titles: [
      ["3 คีย์เวิร์ด Canva ทำรูปสินค้าดูแพงทันที", "Awareness"],
      ["ก่อน-หลัง คลิปนักเรียน ADVANCED ยอดพุ่งหลักแสน", "Conversion"],
      ["ทำไม Babe House ถึงเปิดสถาบันเพื่อผู้หญิงโดยเฉพาะ", "Branding"],
      ["ทรานสิชันลับ 1 ท่า ทำคลิปดูโปรขึ้น 10 เท่า", "Awareness"],
      ["แจก 1 เทคนิคจริงจากคอร์ส ADVANCED ให้ลองทำ", "Conversion"],
      ["รีวิวนักเรียนที่เปลี่ยนจากพนักงานประจำมาเป็นครีเอเตอร์", "Conversion"],
      ["รวมเทมเพลตคุมโทนสายบิวตี้/แฟชั่น", "Awareness"],
      ["เปิด 5 ผลงานเด่นรุ่นล่าสุดคอร์ส ADVANCED", "Branding"],
      ["วันหนึ่งในชีวิตทีมโปรดักชัน Babe House", "Branding"],
      ["3 ความผิดพลาดตอนตัดต่อที่ทำให้คลิปไม่ปัง", "Awareness"],
      ["ใช้ AI เจนพื้นหลังสินค้าให้ดูสตูดิโอแพงๆ", "Awareness"],
      ["ถาม-ตอบ ไม่มีพื้นฐานเลยเรียน ADVANCED ได้ไหม", "Conversion"],
      ["เทียบคลิปคนทั่วไป vs คนที่ผ่านคอร์ส ADVANCED", "Conversion"],
      ["5 ฟอนต์ที่ทำให้แบรนด์ดูพรีเมียม", "Awareness"],
      ["เปิดรอบคอร์ส ADVANCED + โปรพิเศษเดือนนี้", "Conversion"],
      ["Workflow ตัดต่อ 1 คลิปจบใน 20 นาที", "Awareness"],
      ["ทำปก Reels ให้คนกดดูเยอะขึ้น", "Awareness"],
      ["นักเรียนที่ปิดยอดขายสินค้าได้หลังปรับคอนเทนต์", "Conversion"],
      ["คอมมูนิตี้ศิษย์เก่า Babe House ที่โตไปด้วยกัน", "Branding"],
      ["สอนกดสมัครคอร์สผ่าน Link-in-bio ทีละสเต็ป", "Conversion"],
      ["จัดหน้าฟีด IG ให้ดูแพงเป็นแบรนด์เดียวกัน", "Awareness"],
      ["รวมทุกคำถามที่คนถามบ่อยก่อนสมัคร ADVANCED", "Conversion"],
      ["เทคนิคเสียง/จังหวะที่ทำให้คนดูคลิปจนจบ", "Awareness"],
      ["ให้ AI ช่วยคิดแคปชั่นขายของใน 30 วินาที", "Conversion"],
      ["คอร์ส 3,745 บาท คุ้มจริงไหม ตอบตรงๆ ไม่อ้อม", "Conversion"],
      ["Live สด สอนตัดต่อ 1 คลิป + ตอบคำถามคอร์ส", "Branding"],
      ["เป้าหมาย: พาผู้หญิงไทยไปโชว์ผลงานเวทีอินเตอร์", "Branding"],
      ["รวมเสียงรีวิวจริงจากนักเรียนรุ่นที่ผ่านมา", "Conversion"],
      ["ขอบคุณ 12K ครอบครัว Babe House 🩵", "Branding"],
      ["โค้งสุดท้าย! ปิดรับสมัครคอร์ส ADVANCED รอบนี้", "Conversion"],
    ],
    hooks: {
      Awareness: ["หยุดเลื่อนก่อน! สิ่งนี้จะเปลี่ยนคลิปคุณไปตลอด", "เคยสงสัยไหมว่าทำไมคลิปคนอื่นดูแพงกว่า?", "ลองทำตามนี้ คลิปหน้าโปรขึ้นแน่นอน"],
      Conversion: ["ถ้าคุณมีคอนเทนต์แต่ตัดต่อไม่เป็น คลิปนี้เพื่อคุณ", "นักเรียนคนนี้เคยเป็นมือใหม่เหมือนคุณเลย", "อยากให้ครูพี่คิมช่วยพาคุณไปถึงจุดนั้นไหมคะ"],
      Branding: ["เรื่องที่ไม่ค่อยมีใครเล่าเกี่ยวกับ Babe House", "เบื้องหลังที่ทำให้เราเป็นเราในวันนี้", "นี่คือสิ่งที่เราเชื่อมาตลอด"],
    },
    body: {
      Awareness: { say: "จุดสำคัญคือ 3 วินาทีแรกต้องตอบให้ได้ว่าคลิปนี้มีอะไรให้เขา แล้วค่อยพาไปดูเทคนิคทีละสเต็ปแบบทำตามได้จริงค่ะ", ost: "ทำตามได้จริง", vis: "โชว์หน้าจอ + สาธิตทีละขั้น" },
      Conversion: { say: "ปัญหาของหลายคนไม่ใช่ไม่มีของดี แต่คือยังไม่มีระบบที่พาคนดูไปสู่การตัดสินใจ วันนี้ครูพี่คิมจะโชว์ผลลัพธ์จริงให้ดูค่ะ", ost: "ผลลัพธ์จริงจับต้องได้", vis: "before-after + รีวิวนักเรียน" },
      Branding: { say: "Babe House ไม่ได้สอนแค่สกิล แต่เราสร้างคอมมูนิตี้ของผู้หญิงที่อยากเก่งและดูดีไปพร้อมกัน นี่คือตัวตนที่เราภูมิใจค่ะ", ost: "มากกว่าคอร์ส คือคอมมูนิตี้", vis: "เล่าเรื่อง + ภาพทีม/นักเรียน" },
    },
    cta: {
      Awareness: { say: "ถ้าคลิปนี้มีประโยชน์ กดติดตามไว้ พรุ่งนี้ครูพี่คิมมีเทคนิคดีๆ มาให้อีกค่ะ", ost: "กดติดตามไว้นะคะ", vis: "ชี้ปุ่มติดตาม" },
      Conversion: { say: "อยากเรียนตัดต่อให้ทำเองได้ทุกคลิป ทักไลน์ @babehouse_academy หรือกดลิงก์ในไบโอได้เลยค่ะ", ost: "ทักไลน์ / กดลิงก์ในไบโอ", vis: "โชว์ปุ่ม CTA + LINE" },
      Branding: { say: "ถ้าอยากเป็นส่วนหนึ่งของครอบครัว Babe House กดติดตามและทักทายกันได้เลยนะคะ 🩵", ost: "มาเป็นครอบครัวเดียวกัน", vis: "ชี้ปุ่มติดตาม" },
    },
    beat_ts: ["0-3 วิ", "3-45 วิ", "45-60 วิ"],
    hook_ost: "หยุดดูก่อนค่ะ", hook_vis: "พูดหน้ากล้อง / ข้อความใหญ่",
    cap: (t) => `${t} 🩵 #BabeHouseAcademy #ตัดต่อคลิป #ครีเอเตอร์`,
    tip: { Conversion: "คลิป Conversion ต้องจบด้วยคำสั่งเดียวที่ชัดเจน อย่าใส่ CTA หลายอัน", Branding: "เล่าเรื่องจริงจากใจ คนจะรู้สึกผูกพันกับแบรนด์มากกว่าการขายตรงๆ", Awareness: "สอนให้ทำตามได้จริงใน 1 คลิป คนจะเซฟไว้และกลับมาดูซ้ำ" },
    theme: "เพิ่มยอดสมัครคอร์ส + อุดรอยรั่ว Link-in-bio",
    greeting: "สวัสดีค่ะ 🩵 นี่คือ 'ตัวอย่าง' Blueprint เพื่อให้เห็นภาพว่าเล่มจริงจะละเอียดแค่ไหน — เล่มจริงครูพี่คิมจะวิเคราะห์จากช่องและสถิติหลังบ้านของคุณโดยเฉพาะ ทุกบรรทัดคัสตอมเพื่อคุณคนเดียว",
    pillars: ["Hook หยุดนิ้วใน 3 วิ", "Social Proof สร้างความเชื่อ", "CTA พาไปสมัคร", "Link-in-bio ลดรอยรั่ว"],
    snapshot: [
      { emoji: "🎯", label: "เป้าหมายเดือนนี้", value: "เพิ่มยอดสมัครคอร์ส" },
      { emoji: "💎", label: "ระดับตลาด", value: "พรีเมียม" },
      { emoji: "👥", label: "ลูกค้าหลัก", value: "ผู้หญิงวัยทำงาน 25-34" },
      { emoji: "🪢", label: "ปมที่ต้องแก้", value: "คนเห็นแต่ไม่กดต่อ" },
      { emoji: "✨", label: "ของดีที่มี", value: "คอนเทนต์มีคนเชื่อ" },
      { emoji: "🚀", label: "โอกาสโต", value: "เปลี่ยนคนดูเป็นลูกค้า" },
    ],
    what_we_see: [
      "ยอดเข้าถึง 142,000 ครั้ง โดย 61% มาจากคนที่ยังไม่ติดตาม — โอกาสทองในการเปลี่ยนคนแปลกหน้าเป็นแฟน",
      "คนเข้าชมโปรไฟล์ 8,600 ครั้ง แต่กดลิงก์แค่ 540 — มี 'รอยรั่ว' ระหว่างความสนใจกับการกระทำ",
      "Engagement 5.2% สูงกว่าค่าเฉลี่ย แสดงว่าคอนเทนต์โดนใจกลุ่มเป้าหมายจริง",
      "กลุ่มเป้าหมายหลักเป็นผู้หญิง 84% อายุ 25-34 (วัยทำงาน/เริ่มมีกำลังซื้อ)",
      "คลิปสาย How-to และ before-after มี engagement สูงสุด — ควรทำซ้ำเป็นสูตร",
      "ยังไม่มี CTA ที่ชัดในคลิปส่วนใหญ่ — คนดูจบแล้วไม่รู้ว่าต้องทำอะไรต่อ",
    ],
    audience_summary: "ผู้หญิงวัยทำงาน 25-34 ปี ที่อยากพัฒนาสกิลดิจิทัลเพื่อสร้างรายได้เสริมหรือต่อยอดธุรกิจตัวเอง",
    follower_insight: "ผู้ติดตาม 84% เป็นกลุ่มเป้าหมายจริง และ 61% ของ reach มาจาก non-follower = ฐานแฟนใหม่กำลังโตเร็ว",
    market_tier: "Premium",
    positioning: "@babehouse_academy คือสถาบันพรีเมียมที่เปลี่ยน 'คนอยากเก่ง' ให้เป็น 'ครีเอเตอร์ที่ทำเองได้และมีรายได้จริง'",
    kim_insight: "คนที่กดเข้าโปรไฟล์ไม่ใช่คนเย็นแล้ว เขายืนอยู่หน้าประตูบ้านเราแล้ว หน้าที่ของเดือนนี้คือทำ 'ป้ายบอกทาง' ให้ชัดที่สุดว่าเขาต้องกดตรงไหน ทักอะไร และสมัครยังไง — แค่อุดรอยรั่วตรงนี้ ยอดสมัครจะขยับทันทีโดยไม่ต้องเพิ่ม reach เลยค่ะ",
    story: [
      { emoji: "👋", title: "ตอนนี้ช่องคุณเป็นยังไง", body: "ครูพี่คิมแอบส่องช่องคุณมาทั้งวันเลยค่ะ — คนแวะเข้ามาดูโปรไฟล์เยอะมาก แปลว่าคอนเทนต์คุณมีเสน่ห์จนคนอยากรู้จักต่อ แต่พอถึงจังหวะที่เขาจะ 'ก้าวต่อ' กลับยังไม่เจอทางเดินที่ชัด เลยหลุดมือไปอย่างน่าเสียดายค่ะ" },
      { emoji: "💎", title: "เสน่ห์ที่คุณอาจไม่รู้ตัว", body: "คุณมีของจริงและมีคนกลุ่มหนึ่งที่เชื่อในตัวคุณอยู่แล้ว นี่คือต้นทุนล้ำค่าที่เงินซื้อไม่ได้ค่ะ เราแค่ต้องหยิบมันออกมาวางให้ถูกที่ ถูกจังหวะเท่านั้นเอง" },
      { emoji: "🪢", title: "ปมเล็กๆ ที่ฉุดไว้", body: "ปัญหาตอนนี้ไม่ใช่ 'คนไม่เห็น' นะคะ แต่คือคนเห็นแล้วไม่รู้ว่าต้องทำอะไรต่อ — เหมือนมีคนมายืนหน้าร้านเต็มไปหมด แต่ไม่มีป้ายบอกว่าประตูเข้าอยู่ตรงไหน" },
      { emoji: "🌈", title: "โอกาสทองที่รออยู่", body: "ข่าวดีคือพอเราติดป้ายบอกทางให้ชัด ยอดสมัครจะขยับขึ้นทันทีโดยที่ยังไม่ต้องเหนื่อยหาคนใหม่เลยค่ะ คนที่มีอยู่แล้วนี่แหละคือขุมทรัพย์ของเดือนนี้" },
      { emoji: "🗺️", title: "30 วันนี้เราจะไปด้วยกัน", body: "ครูพี่คิมวางสคริปต์ให้ครบทั้ง 30 วันแล้ว ค่อยๆ ทำวันละคลิป ไม่ต้องรีบ ไม่ต้องเพอร์เฟกต์ ขอแค่ทำสม่ำเสมอ แล้วคุณจะเห็นช่องค่อยๆ เปลี่ยนไปเองค่ะ" },
      { emoji: "💌", title: "จากใจครูพี่คิม", body: "คุณมาไกลกว่าที่ตัวเองคิดเยอะเลยนะคะ เดือนนี้เราจะจับมือกันอุดรอยรั่วทีละจุด ครูพี่คิมเป็นกำลังใจให้เสมอค่ะ 🩵" },
    ],
    swot: {
      strengths: ["คอนเทนต์มีคุณภาพ engagement 5.2% สูงกว่าค่าเฉลี่ยตลาด", "มีฐานแฟนจริง 84% + reach จากคนใหม่ 61% = ฐานกำลังโตเร็ว", "แบรนด์มีจุดยืน Premium และ Social Proof ที่ชัดเจนตั้งแต่ต้น", "กลุ่มเป้าหมายชัด (ผู้หญิงวัยทำงาน) ทำให้สื่อสารและการตลาดแม่นยำ", "มีวิสัยทัศน์ Go International + คอมมูนิตี้ที่เป็นเอกลักษณ์"],
      weaknesses: ["ไม่มีระบบ CTA ที่ชัด ทำให้ conversion ต่ำกว่าศักยภาพ", "Link-in-bio ยังไม่ถูกออกแบบให้ปิดการขายเป็นขั้นตอน", "ยังพึ่งกระแส/แรงบันดาลใจมากกว่าระบบคอนเทนต์ที่ทำซ้ำได้", "คอนเทนต์ส่วนใหญ่เป็นไทย อาจยังไม่ตอบวิสัยทัศน์ Go International", "การทำ Marathon ระยะยาวต้องการระบบสนับสนุน + คอนเทนต์ต่อเนื่องสูง"],
      opportunities: ["เปลี่ยน non-follower 61% เป็นแฟนด้วยคอนเทนต์ Social Proof", "ทำคอร์ส/แพ็กเกจเฉพาะกลุ่มวัยทำงานที่มีกำลังซื้อ", "ขยายสู่บริการ Production สำหรับคนไม่มีเวลาทำเอง", "พัฒนา Community เป็นแหล่งรวม 'Marathon Learner' สร้าง Brand Loyalty", "ใช้ AI สร้างคอนเทนต์/เครื่องมือช่วยสอน เพิ่มประสิทธิภาพและความน่าสนใจ"],
      threats: ["คู่แข่งสายราคาถูกเข้ามาตัดราคาในตลาดสอนทักษะ", "อัลกอริทึมเปลี่ยนบ่อย ทำให้ reach ผันผวน", "ภาพ Premium อาจถูกลดทอนถ้าสื่อสารคุณค่าไม่ชัด", "เทคโนโลยี (AI/โปรแกรม) เปลี่ยนเร็ว ต้องอัปเดตหลักสูตรตลอด", "Learning Fatigue ของผู้เรียนถ้าคอนเทนต์ไม่กระตุ้นต่อเนื่อง"],
    },
    modules: {
      archetype: { name: "The Mentor–Muse · ผู้ชี้ทางสายพรีเมียม", body: "ยืนบนจุดตัดของ 'The Sage/Mentor' (ผู้รู้ที่หยิบยื่นทางลัด) กับ 'The Creator/Muse' (แรงบันดาลใจด้านความงาม) — ทำให้แบรนด์ไม่ใช่แค่คอร์สสอนสกิล แต่เป็นพื้นที่ปลอดภัยของผู้หญิงที่อยากเก่งและดูดีไปพร้อมกัน", tone: "อบอุ่นแบบพี่สาวที่เก่งจริงและใจดี พูดเหมือนกระซิบเคล็ดลับให้เพื่อนสนิทฟัง ไม่สั่งสอนแบบครูหน้าห้อง สลับประโยคชวนฝันกับประโยคที่ทำตามได้จริงทันที ลงท้ายด้วย ค่ะ/นะคะ", look: "คุมโทนสีเป็นซิกเนเจอร์เดียวทั้งช่อง (ครีม–ฟ้านวล–ชมพูพาสเทล) เสื้อผ้าเรียบมีดีเทล แต่งหน้าลุคใส ฉากหลังสะอาดมีพร็อพคุมโทน แสงนุ่มจากธรรมชาติ — ทุกองค์ประกอบส่งสัญญาณ 'พรีเมียมแต่เข้าถึงได้'" },
      avatar: { name: "น้องบี อายุ 26 · พนักงานออฟฟิศอยากมีรายได้เสริม", think: "อยากเก่งขึ้น อยากมีสกิลติดตัวที่ใช้สร้างรายได้ และอยากมีชีวิตที่ดีขึ้นในทุกๆ ด้าน", see: "เห็นคนอื่นทำคอนเทนต์สวยๆ ตัดต่อเก่งๆ แล้วรู้สึกอยากทำได้บ้าง เห็นโอกาสทางธุรกิจจากทักษะดิจิทัล", hear: "ได้ยินว่าต้องทำคลิปถึงจะมีตัวตน แต่ไม่รู้จะเริ่มตรงไหน กลัวทำออกมาแล้วไม่ดี", fear: "กลัวว่าจะไม่ทันโลก กลัวลงทุนเรียนแล้วทำไม่ได้จริง และกลัวเป็นคนที่หยุดอยู่กับที่", hookbank: ["ทำคลิปมาเป็นสิบ ยอดยังไม่ขึ้น เพราะอะไร?", "ช่องดูดีแต่ขายไม่ได้ แก้ตรงนี้เลย", "ไม่มีพื้นฐานก็ทำคลิปดูแพงได้นะ", "อยากมีรายได้เสริมจากสกิลดิจิทัลไหม?"] },
      competitor: { intro: "ตลาดสอนทักษะดิจิทัลแบ่งเป็น 3 กลุ่มหลัก แต่ละกลุ่มมีจุดอ่อนที่เราเติมเต็มได้", rows: [{ name: "สถาบันสอนทั่วไป", they: "คอร์สหลากหลาย เน้นปริมาณและราคาถูก สอนเครื่องมือกว้างๆ", gap: "เราเหนือกว่าด้วยการจับมือทำจริง + คอมมูนิตี้ + โฟกัสผู้หญิงโดยเฉพาะ" }, { name: "โค้ช Personal Branding/อินฟลู", they: "เน้นสร้างตัวตนและเล่าเรื่องส่วนตัวเป็น Social Proof", gap: "เราเหนือกว่าด้วยสกิลตัดต่อเชิงลึกแบบ Production House จริง" }, { name: "คอร์สฟรี/คลิปสอนใน YouTube", they: "เนื้อหาฟรีแต่กระจัดกระจาย ไม่มีระบบ ไม่มีคนคอยจับมือ", gap: "เราเหนือกว่าด้วยหลักสูตรเป็นขั้นตอน + ผลลัพธ์ที่วัดได้ + พี่เลี้ยงตัวจริง" }], blueocean: "Babe House = 'The Ultimate Premium Ecosystem for Women' ที่ผสานสกิลตัดต่อระดับโปรดักชัน + Personal Branding ที่จับต้องได้ + คอมมูนิตี้ระยะยาวสู่เวทีอินเตอร์" },
      values: { list: ["Support over Sales", "Premium is a Feeling", "We Rise Together"], manifesto: "Babe House เชื่อว่าผู้หญิงทุกคนมีศักยภาพในการสร้างคอนเทนต์ที่ดูแพงและเปลี่ยนชีวิตได้ เมื่อมีระบบที่ถูกต้องและมีคนจับมือเดินไปด้วยกัน" },
      funnel: { top: { label: "TOP", pct: 30, body: "ดักคนใหม่ด้วย How-to/เทคนิคฟรี" }, middle: { label: "MIDDLE", pct: 50, body: "สร้างความเชื่อด้วยรีวิว/before-after" }, bottom: { label: "BOTTOM", pct: 20, body: "ปิดการขายด้วย CTA + โปรรอบ" }, note: "อย่าขายติดกันรัว เลี้ยงความเชื่อด้วย Social Proof ก่อนปิดการขายค่ะ" },
    },
  },
  en: {
    titles: [
      ["3 Canva keywords that make product photos look expensive instantly", "Awareness"],
      ["Before & after: an ADVANCED student's clip hits 100k+ views", "Conversion"],
      ["Why Babe House opened a school just for women", "Branding"],
      ["1 secret transition that makes clips look 10× more pro", "Awareness"],
      ["A real technique from the ADVANCED course — try it yourself", "Conversion"],
      ["A student who went from 9-to-5 to creator", "Conversion"],
      ["Color-tone templates for beauty/fashion", "Awareness"],
      ["5 standout works from the latest ADVANCED batch", "Branding"],
      ["A day in the life of the Babe House production team", "Branding"],
      ["3 editing mistakes that keep your clips from popping", "Awareness"],
      ["Use AI to generate studio-quality product backgrounds", "Awareness"],
      ["Q&A: can total beginners take ADVANCED?", "Conversion"],
      ["Average clip vs a clip after the ADVANCED course", "Conversion"],
      ["5 fonts that make a brand look premium", "Awareness"],
      ["ADVANCED course is open + this month's special offer", "Conversion"],
      ["An editing workflow that finishes a clip in 20 minutes", "Awareness"],
      ["Make Reels covers that get more taps", "Awareness"],
      ["A student who closed sales after reworking her content", "Conversion"],
      ["The Babe House alumni community growing together", "Branding"],
      ["How to sign up via Link-in-bio, step by step", "Conversion"],
      ["Style your IG feed to look like one premium brand", "Awareness"],
      ["Every FAQ people ask before joining ADVANCED", "Conversion"],
      ["Audio & pacing tricks that keep viewers to the end", "Awareness"],
      ["Let AI write a selling caption in 30 seconds", "Conversion"],
      ["Is the ฿3,745 course really worth it? An honest answer", "Conversion"],
      ["Live: editing a clip + course Q&A", "Branding"],
      ["Our goal: take women to the international stage", "Branding"],
      ["Real reviews from past students", "Conversion"],
      ["Thank you, 12K Babe House family 🩵", "Branding"],
      ["Last call! ADVANCED enrollment closes this round", "Conversion"],
    ],
    hooks: {
      Awareness: ["Stop scrolling — this will change your clips forever", "Ever wonder why other people's clips look more expensive?", "Try this and your next clip will look way more pro"],
      Conversion: ["If you have content but can't edit, this clip is for you", "This student was a total beginner — just like you", "Want Kim to help you get there?"],
      Branding: ["A story not many tell about Babe House", "The behind-the-scenes that made us who we are", "This is what we've always believed"],
    },
    body: {
      Awareness: { say: "The key is the first 3 seconds — make it clear what's in it for them, then walk through the technique step by step so they can actually follow along.", ost: "Easy to follow", vis: "Screen recording + step-by-step demo" },
      Conversion: { say: "For most people the problem isn't a lack of substance — it's not having a system that guides viewers to a decision. Today I'll show you real results.", ost: "Tangible real results", vis: "Before-after + student reviews" },
      Branding: { say: "Babe House doesn't just teach skills — we build a community of women who want to be skilled and look good at the same time. This is the identity we're proud of.", ost: "More than a course — a community", vis: "Storytelling + team/student shots" },
    },
    cta: {
      Awareness: { say: "If this helped, hit follow — tomorrow I've got more great tips for you.", ost: "Hit follow", vis: "Point to the follow button" },
      Conversion: { say: "Want to learn editing so you can do every clip yourself? DM @babehouse_academy or tap the link in bio.", ost: "DM us / tap link in bio", vis: "Show the CTA button + LINE" },
      Branding: { say: "If you'd like to be part of the Babe House family, follow and say hi 🩵", ost: "Join the family", vis: "Point to the follow button" },
    },
    beat_ts: ["0-3 sec", "3-45 sec", "45-60 sec"],
    hook_ost: "Stop and watch", hook_vis: "Talk to camera / big text",
    cap: (t) => `${t} 🩵 #BabeHouseAcademy #VideoEditing #ContentCreator`,
    tip: { Conversion: "A conversion clip must end with one clear command — don't stack multiple CTAs.", Branding: "Tell a real story from the heart; people bond with the brand far more than with hard selling.", Awareness: "Teach something doable in one clip — people save it and rewatch." },
    theme: "More course sign-ups + plug the Link-in-bio leak",
    greeting: "Hi there 🩵 This is a 'sample' Blueprint so you can see how detailed the real one gets — in your real book, Kim analyzes your own channel and Insights specifically, with every line customized just for you.",
    pillars: ["A 3-second scroll-stopping hook", "Social proof that builds trust", "A CTA that drives sign-ups", "Link-in-bio that plugs the leak"],
    snapshot: [
      { emoji: "🎯", label: "This month's goal", value: "More course sign-ups" },
      { emoji: "💎", label: "Market tier", value: "Premium" },
      { emoji: "👥", label: "Core audience", value: "Working women 25-34" },
      { emoji: "🪢", label: "The knot to untie", value: "Seen, but no next step" },
      { emoji: "✨", label: "Your hidden gem", value: "Content people trust" },
      { emoji: "🚀", label: "Growth opportunity", value: "Turn viewers into customers" },
    ],
    what_we_see: [
      "142,000 reach, with 61% from non-followers — a golden chance to turn strangers into fans",
      "8,600 profile visits but only 540 link taps — there's a 'leak' between interest and action",
      "5.2% engagement, above average — your content genuinely resonates with your audience",
      "Your core audience is 84% women aged 25-34 (working age, starting to have buying power)",
      "How-to and before-after clips get the highest engagement — repeat them as a formula",
      "Most clips lack a clear CTA — viewers finish and don't know what to do next",
    ],
    audience_summary: "Working women aged 25-34 who want to build digital skills for extra income or to grow their own business.",
    follower_insight: "84% of followers are your true target, and 61% of reach comes from non-followers = a new fan base growing fast.",
    market_tier: "Premium",
    positioning: "@babehouse_academy is the premium school that turns 'people who want to be skilled' into 'creators who can do it themselves and earn for real'.",
    kim_insight: "People who tap into your profile aren't cold anymore — they're standing at your front door. This month's job is to put up the clearest 'signpost' showing exactly where to tap, what to message, and how to sign up. Plug this one leak and sign-ups move immediately — without adding any reach.",
    story: [
      { emoji: "👋", title: "Where your channel stands", body: "I've been quietly studying your channel all day — lots of people visit your profile, which means your content is charming enough to make them curious. But when it's time to take the next step, they can't find a clear path, so they slip away. Such a shame." },
      { emoji: "💎", title: "A charm you may not notice", body: "You have real substance and a group of people who already believe in you. That's priceless capital money can't buy — we just need to place it in the right spot at the right time." },
      { emoji: "🪢", title: "The small knot holding you back", body: "The problem isn't that people don't see you — it's that they see you and don't know what to do next. Like a crowd in front of your shop with no sign showing where the door is." },
      { emoji: "🌈", title: "The golden opportunity waiting", body: "The good news: once we put up a clear signpost, sign-ups rise immediately — without tiring yourself chasing new people. The audience you already have is this month's treasure." },
      { emoji: "🗺️", title: "These 30 days, we go together", body: "I've laid out all 30 days of scripts. Take it one clip a day — no rush, no need to be perfect. Just be consistent, and you'll watch your channel transform on its own." },
      { emoji: "💌", title: "From Kim's heart", body: "You've come further than you think. This month we'll plug the leaks one by one, together. I'm always cheering you on 🩵" },
    ],
    swot: {
      strengths: ["Quality content with 5.2% engagement, above market average", "A real fan base (84%) + 61% reach from new people = base growing fast", "A clear Premium positioning and social proof from the start", "A clear audience (working women) makes messaging and marketing precise", "A Go-International vision + a distinctive community"],
      weaknesses: ["No clear CTA system, so conversion is below potential", "Link-in-bio isn't designed to close sales step by step", "Still relies on trends/inspiration more than a repeatable content system", "Most content is in Thai, which may not yet serve the Go-International vision", "A long Marathon needs a support system + high content consistency"],
      opportunities: ["Turn the 61% non-followers into fans with social-proof content", "Create courses/packages for the working-age, higher-spending group", "Expand into Production services for those with no time to do it themselves", "Grow the community into a hub of 'Marathon Learners' to build brand loyalty", "Use AI to create content/teaching tools for more efficiency and appeal"],
      threats: ["Low-price competitors undercutting the skills-teaching market", "Frequent algorithm changes making reach volatile", "The Premium image can erode if value isn't communicated clearly", "Technology (AI/software) changes fast — the curriculum must keep updating", "Learner fatigue if content doesn't keep motivating"],
    },
    modules: {
      archetype: { name: "The Mentor–Muse · the premium guide", body: "Standing at the intersection of 'The Sage/Mentor' (the expert who hands over shortcuts) and 'The Creator/Muse' (beauty-driven inspiration) — making the brand not just a skills course but a safe space for women who want to be skilled and look good at once.", tone: "Warm like a truly skilled, kind older sister — speaking as if whispering tips to a close friend, never lecturing. Alternate dreamy lines with immediately actionable ones.", look: "One signature color tone across the whole channel (cream–soft blue–pastel pink), simple clothing with detail, fresh-faced makeup, clean backgrounds with tonal props, soft natural light — every element signals 'premium yet approachable'." },
      avatar: { name: "Bee, 26 · office worker wanting extra income", think: "Wants to get better, to have a skill that earns, and a better life in every way", see: "Sees others making beautiful, well-edited content and wishes she could too; sees business opportunity in digital skills", hear: "Hears you must make clips to have a presence, but doesn't know where to start, afraid it won't turn out good", fear: "Afraid of falling behind, of investing in a course and not being able to do it, of standing still", hookbank: ["Made dozens of clips and views still won't budge — why?", "Channel looks good but doesn't sell — fix this", "No experience? You can still make clips look expensive", "Want extra income from digital skills?"] },
      competitor: { intro: "The digital-skills market splits into 3 groups, each with a gap we fill", rows: [{ name: "General training schools", they: "Many courses, quantity- and price-focused, teaching tools broadly", gap: "We win with hands-on doing + community + a women-only focus" }, { name: "Personal-branding coaches/influencers", they: "Focus on identity and personal storytelling as social proof", gap: "We win with deep, real production-house editing skills" }, { name: "Free courses/YouTube tutorials", they: "Free but scattered, no system, no one to guide you", gap: "We win with a step-by-step curriculum + measurable results + a real mentor" }], blueocean: "Babe House = 'The Ultimate Premium Ecosystem for Women', blending production-level editing + tangible personal branding + a long-term community heading for the international stage" },
      values: { list: ["Support over Sales", "Premium is a Feeling", "We Rise Together"], manifesto: "Babe House believes every woman has the potential to create expensive-looking, life-changing content — when she has the right system and someone to walk with her." },
      funnel: { top: { label: "TOP", pct: 30, body: "Catch new people with free how-tos/techniques" }, middle: { label: "MIDDLE", pct: 50, body: "Build trust with reviews/before-after" }, bottom: { label: "BOTTOM", pct: 20, body: "Close with a CTA + a timed offer" }, note: "Don't sell back-to-back — nurture trust with social proof before closing." },
    },
  },
};

export function sampleBlueprint(lang = "th") {
  const d = DATA[lang === "en" ? "en" : "th"];
  const calendar = d.titles.map(([t, g], i) => ({ d: i + 1, g, t, h: d.hooks[g][i % 3], f: g === "Conversion" ? "Reels + CTA" : g === "Branding" ? "Storytelling" : "How-to Reels" }));
  const scripts = calendar.map((c) => ({
    d: c.d, g: c.g,
    beats: [
      { ts: d.beat_ts[0], s: "HOOK", say: c.h, ost: d.hook_ost, vis: d.hook_vis },
      { ts: d.beat_ts[1], s: "BODY", ...d.body[c.g] },
      { ts: d.beat_ts[2], s: "CTA", ...d.cta[c.g] },
    ],
    cap: d.cap(c.t),
    tip: d.tip[c.g],
  }));
  return {
    instagram_account: "@babehouse_academy", theme: d.theme, greeting: d.greeting, pillars: d.pillars,
    snapshot: d.snapshot, what_we_see: d.what_we_see, audience_summary: d.audience_summary,
    follower_insight: d.follower_insight, market_tier: d.market_tier, positioning: d.positioning,
    kim_insight: d.kim_insight, story: d.story, swot: d.swot, modules: d.modules,
    calendar, scripts,
    metrics: { followers: 12400, reach: 142000, profile_visits: 8600, link_taps: 540, engagement_rate: 5.2 },
  };
}
